name: Rust

on:
  push:
    branches: [ "rust-rewrite" ]
  pull_request:
    branches: [ "rust-rewrite" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --release
    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Run tests
      run: cargo test
    - name: UPX GitHub Action
      uses: crazy-max/ghaction-upx@v2.2.0
      with:
        args: --best --lzma
        files: |
          target/release/pocbot
    - name: Publish artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Build Files
        path: |
          target/release/pocbot
