name: Rust

on:
  push:
    branches: ["rust-rewrite"]
  pull_request:
    branches: ["rust-rewrite"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --release

      - name: UPX GitHub Action
        uses: crazy-max/ghaction-upx@v2.2.0
        with:
          args: --best --lzma
          files: |
            target/release/pocbot

      - name: Publish artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Build Files
          path: |
            target/release/pocbot

      - name: Build Docker Image
        run: |
          docker buildx create --use
          docker buildx build --platform linux/amd64 -t ghcr.io/openplayverse/pocbot:latest -f Dockerfile .

      - name: Login to GitHub Container Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push Docker Image to GitHub Container Registry
        run: docker buildx build --platform linux/amd64 -t ghcr.io/openplayverse/pocbot:latest -f Dockerfile . --push
